ALTER TABLE rote2real_students
    ADD COLUMN IF NOT EXISTS university_name VARCHAR(200) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS course_degree VARCHAR(200) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS year_of_study VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS track VARCHAR(100) NOT NULL DEFAULT 'Generative AI';
